/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "A-DT-apdu.h"

static asn_TYPE_member_t asn_MBR_A_DT_apdu_1[] = {
	{ ATF_POINTER, 3, offsetof(struct A_DT_apdu, aso_qualifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASO_qualifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aso-qualifier"
		},
	{ ATF_POINTER, 2, offsetof(struct A_DT_apdu, asoi_identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASOI_identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"asoi-identifier"
		},
	{ ATF_POINTER, 1, offsetof(struct A_DT_apdu, a_user_data),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_User_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"a-user-data"
		},
};
static const ber_tlv_tag_t asn_DEF_A_DT_apdu_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_A_DT_apdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aso-qualifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* asoi-identifier */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 2, 0, 0 } /* a-user-data */
};
static asn_SEQUENCE_specifics_t asn_SPC_A_DT_apdu_specs_1 = {
	sizeof(struct A_DT_apdu),
	offsetof(struct A_DT_apdu, _asn_ctx),
	asn_MAP_A_DT_apdu_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_A_DT_apdu = {
	"A-DT-apdu",
	"A-DT-apdu",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_A_DT_apdu_tags_1,
	sizeof(asn_DEF_A_DT_apdu_tags_1)
		/sizeof(asn_DEF_A_DT_apdu_tags_1[0]) - 1, /* 1 */
	asn_DEF_A_DT_apdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_A_DT_apdu_tags_1)
		/sizeof(asn_DEF_A_DT_apdu_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_A_DT_apdu_1,
	3,	/* Elements count */
	&asn_SPC_A_DT_apdu_specs_1	/* Additional specs */
};

