/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_A_DT_apdu_H_
#define	_A_DT_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASOI-identifier.h"
#include "User-Data.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASO_qualifier;
struct User_Data;

/* A-DT-apdu */
typedef struct A_DT_apdu {
	struct ASO_qualifier	*aso_qualifier	/* OPTIONAL */;
	ASOI_identifier_t	*asoi_identifier	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct User_Data	*a_user_data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} A_DT_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_A_DT_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASO-qualifier.h"

#endif	/* _A_DT_apdu_H_ */
#include <asn_internal.h>
