/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AARE_apdu_H_
#define	_AARE_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "ASO-context-name.h"
#include "Associate-result.h"
#include "Associate-source-diagnostic.h"
#include "AP-invocation-identifier.h"
#include "AE-invocation-identifier.h"
#include "ACSE-requirements.h"
#include "Mechanism-name.h"
#include "Implementation-data.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AARE_apdu__protocol_version {
	AARE_apdu__protocol_version_version1	= 0
} e_AARE_apdu__protocol_version;

/* Forward declarations */
struct AP_title;
struct ASO_qualifier;
struct Authentication_value;
struct ASO_context_name_list;
struct P_context_result_list;
struct ASOI_tag;
struct Association_data;

/* AARE-apdu */
typedef struct AARE_apdu {
	BIT_STRING_t	*protocol_version	/* DEFAULT {version1} */;
	ASO_context_name_t	 aSO_context_name;
	Associate_result_t	 result;
	Associate_source_diagnostic_t	 result_source_diagnostic;
	struct AP_title	*responding_AP_title	/* OPTIONAL */;
	struct ASO_qualifier	*responding_AE_qualifier	/* OPTIONAL */;
	AP_invocation_identifier_t	*responding_AP_invocation_identifier	/* OPTIONAL */;
	AE_invocation_identifier_t	*responding_AE_invocation_identifier	/* OPTIONAL */;
	ACSE_requirements_t	*responder_acse_requirements	/* OPTIONAL */;
	Mechanism_name_t	*mechanism_name	/* OPTIONAL */;
	struct Authentication_value	*responding_authentication_value	/* OPTIONAL */;
	struct ASO_context_name_list	*aSO_context_name_list	/* OPTIONAL */;
	Implementation_data_t	*implementation_information	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct P_context_result_list	*p_context_result_list	/* OPTIONAL */;
	struct ASOI_tag	*called_asoi_tag	/* OPTIONAL */;
	struct ASOI_tag	*calling_asoi_tag	/* OPTIONAL */;
	struct Association_data	*user_information	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AARE_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AARE_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AP-title.h"
#include "AE-qualifier.h"
#include "Authentication-value.h"
#include "ASO-context-name-list.h"
#include "P-context-result-list.h"
#include "ASOI-tag.h"
#include "Association-data.h"

#endif	/* _AARE_apdu_H_ */
#include <asn_internal.h>
