/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AARQ_apdu_H_
#define	_AARQ_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "ASO-context-name.h"
#include "AP-invocation-identifier.h"
#include "AE-invocation-identifier.h"
#include "ACSE-requirements.h"
#include "Mechanism-name.h"
#include "Implementation-data.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AARQ_apdu__protocol_version {
	AARQ_apdu__protocol_version_version1	= 0
} e_AARQ_apdu__protocol_version;

/* Forward declarations */
struct AP_title;
struct ASO_qualifier;
struct Authentication_value;
struct ASO_context_name_list;
struct Syntactic_context_list;
struct ASOI_tag;
struct Association_data;

/* AARQ-apdu */
typedef struct AARQ_apdu {
	BIT_STRING_t	*protocol_version	/* DEFAULT {version1} */;
	ASO_context_name_t	 aSO_context_name;
	struct AP_title	*called_AP_title	/* OPTIONAL */;
	struct ASO_qualifier	*called_AE_qualifier	/* OPTIONAL */;
	AP_invocation_identifier_t	*called_AP_invocation_identifier	/* OPTIONAL */;
	AE_invocation_identifier_t	*called_AE_invocation_identifier	/* OPTIONAL */;
	struct AP_title	*calling_AP_title	/* OPTIONAL */;
	struct ASO_qualifier	*calling_AE_qualifier	/* OPTIONAL */;
	AP_invocation_identifier_t	*calling_AP_invocation_identifier	/* OPTIONAL */;
	AE_invocation_identifier_t	*calling_AE_invocation_identifier	/* OPTIONAL */;
	ACSE_requirements_t	*sender_acse_requirements	/* OPTIONAL */;
	Mechanism_name_t	*mechanism_name	/* OPTIONAL */;
	struct Authentication_value	*calling_authentication_value	/* OPTIONAL */;
	struct ASO_context_name_list	*aSO_context_name_list	/* OPTIONAL */;
	Implementation_data_t	*implementation_information	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Syntactic_context_list	*p_context_definition_list	/* OPTIONAL */;
	struct ASOI_tag	*called_asoi_tag	/* OPTIONAL */;
	struct ASOI_tag	*calling_asoi_tag	/* OPTIONAL */;
	struct Association_data	*user_information	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AARQ_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AARQ_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AP-title.h"
#include "AE-qualifier.h"
#include "Authentication-value.h"
#include "ASO-context-name-list.h"
#include "Syntactic-context-list.h"
#include "ASOI-tag.h"
#include "Association-data.h"

#endif	/* _AARQ_apdu_H_ */
#include <asn_internal.h>
