/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ACRQ_apdu_H_
#define	_ACRQ_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASOI-identifier.h"
#include "ASO-context-name.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASO_qualifier;
struct ASO_context_name_list;
struct Syntactic_context_list;
struct Association_data;

/* ACRQ-apdu */
typedef struct ACRQ_apdu {
	struct ASO_qualifier	*aso_qualifier	/* OPTIONAL */;
	ASOI_identifier_t	*asoi_identifier	/* OPTIONAL */;
	ASO_context_name_t	*aSO_context_name	/* OPTIONAL */;
	struct ASO_context_name_list	*aSO_context_name_list	/* OPTIONAL */;
	struct Syntactic_context_list	*p_context_definition_list	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Association_data	*user_information	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ACRQ_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACRQ_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASO-qualifier.h"
#include "ASO-context-name-list.h"
#include "Syntactic-context-list.h"
#include "User-information.h"

#endif	/* _ACRQ_apdu_H_ */
#include <asn_internal.h>
