/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ACRQ-apdu.h"

static asn_TYPE_member_t asn_MBR_ACRQ_apdu_1[] = {
	{ ATF_POINTER, 6, offsetof(struct ACRQ_apdu, aso_qualifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASO_qualifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aso-qualifier"
		},
	{ ATF_POINTER, 5, offsetof(struct ACRQ_apdu, asoi_identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASOI_identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"asoi-identifier"
		},
	{ ATF_POINTER, 4, offsetof(struct ACRQ_apdu, aSO_context_name),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASO_context_name,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aSO-context-name"
		},
	{ ATF_POINTER, 3, offsetof(struct ACRQ_apdu, aSO_context_name_list),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASO_context_name_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aSO-context-name-list"
		},
	{ ATF_POINTER, 2, offsetof(struct ACRQ_apdu, p_context_definition_list),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Syntactic_context_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"p-context-definition-list"
		},
	{ ATF_POINTER, 1, offsetof(struct ACRQ_apdu, user_information),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_User_information,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"user-information"
		},
};
static const ber_tlv_tag_t asn_DEF_ACRQ_apdu_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ACRQ_apdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aso-qualifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* asoi-identifier */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* aSO-context-name */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* aSO-context-name-list */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* p-context-definition-list */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 5, 0, 0 } /* user-information */
};
static asn_SEQUENCE_specifics_t asn_SPC_ACRQ_apdu_specs_1 = {
	sizeof(struct ACRQ_apdu),
	offsetof(struct ACRQ_apdu, _asn_ctx),
	asn_MAP_ACRQ_apdu_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ACRQ_apdu = {
	"ACRQ-apdu",
	"ACRQ-apdu",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ACRQ_apdu_tags_1,
	sizeof(asn_DEF_ACRQ_apdu_tags_1)
		/sizeof(asn_DEF_ACRQ_apdu_tags_1[0]) - 1, /* 1 */
	asn_DEF_ACRQ_apdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_ACRQ_apdu_tags_1)
		/sizeof(asn_DEF_ACRQ_apdu_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ACRQ_apdu_1,
	6,	/* Elements count */
	&asn_SPC_ACRQ_apdu_specs_1	/* Additional specs */
};

