/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AE_qualifier_H_
#define	_AE_qualifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASO-qualifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AE-qualifier */
typedef ASO_qualifier_t	 AE_qualifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AE_qualifier;
asn_struct_free_f AE_qualifier_free;
asn_struct_print_f AE_qualifier_print;
asn_constr_check_f AE_qualifier_constraint;
ber_type_decoder_f AE_qualifier_decode_ber;
der_type_encoder_f AE_qualifier_encode_der;
xer_type_decoder_f AE_qualifier_decode_xer;
xer_type_encoder_f AE_qualifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AE_qualifier_H_ */
#include <asn_internal.h>
