/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AP-title.h"

static asn_TYPE_member_t asn_MBR_AP_title_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AP_title, choice.ap_title_form1),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_AP_title_form1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ap-title-form1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AP_title, choice.ap_title_form2),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_AP_title_form2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ap-title-form2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AP_title, choice.ap_title_form3),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_AP_title_form3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ap-title-form3"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AP_title_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* ap-title-form2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* rdnSequence */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 2, 0, 0 } /* ap-title-form3 */
};
static asn_CHOICE_specifics_t asn_SPC_AP_title_specs_1 = {
	sizeof(struct AP_title),
	offsetof(struct AP_title, _asn_ctx),
	offsetof(struct AP_title, present),
	sizeof(((struct AP_title *)0)->present),
	asn_MAP_AP_title_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AP_title = {
	"AP-title",
	"AP-title",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_AP_title_1,
	3,	/* Elements count */
	&asn_SPC_AP_title_specs_1	/* Additional specs */
};

