/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ASO_context_name_list_H_
#define	_ASO_context_name_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASO-context-name.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ASO-context-name-list */
typedef struct ASO_context_name_list {
	A_SEQUENCE_OF(ASO_context_name_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASO_context_name_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASO_context_name_list;

#ifdef __cplusplus
}
#endif

#endif	/* _ASO_context_name_list_H_ */
#include <asn_internal.h>
