/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ASO_qualifier_form3_H_
#define	_ASO_qualifier_form3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ASO-qualifier-form3 */
typedef PrintableString_t	 ASO_qualifier_form3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASO_qualifier_form3;
asn_struct_free_f ASO_qualifier_form3_free;
asn_struct_print_f ASO_qualifier_form3_print;
asn_constr_check_f ASO_qualifier_form3_constraint;
ber_type_decoder_f ASO_qualifier_form3_decode_ber;
der_type_encoder_f ASO_qualifier_form3_encode_der;
xer_type_decoder_f ASO_qualifier_form3_decode_xer;
xer_type_encoder_f ASO_qualifier_form3_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ASO_qualifier_form3_H_ */
#include <asn_internal.h>
