/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ASO-qualifier.h"

static asn_TYPE_member_t asn_MBR_ASO_qualifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASO_qualifier, choice.aso_qualifier_form1),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_ASO_qualifier_form1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aso-qualifier-form1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASO_qualifier, choice.aso_qualifier_form2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ASO_qualifier_form2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aso-qualifier-form2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASO_qualifier, choice.aso_qualifier_form3),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_ASO_qualifier_form3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aso-qualifier-form3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASO_qualifier, choice.aso_qualifier_form_any_octets),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ASO_qualifier_form_octets,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aso-qualifier-form-any-octets"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASO_qualifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* aso-qualifier-form2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* aso-qualifier-form-any-octets */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 0, 0, 0 }, /* aso-qualifier-form1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 2, 0, 0 } /* aso-qualifier-form3 */
};
static asn_CHOICE_specifics_t asn_SPC_ASO_qualifier_specs_1 = {
	sizeof(struct ASO_qualifier),
	offsetof(struct ASO_qualifier, _asn_ctx),
	offsetof(struct ASO_qualifier, present),
	sizeof(((struct ASO_qualifier *)0)->present),
	asn_MAP_ASO_qualifier_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ASO_qualifier = {
	"ASO-qualifier",
	"ASO-qualifier",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ASO_qualifier_1,
	4,	/* Elements count */
	&asn_SPC_ASO_qualifier_specs_1	/* Additional specs */
};

