/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ASO_qualifier_H_
#define	_ASO_qualifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASO-qualifier-form1.h"
#include "ASO-qualifier-form2.h"
#include "ASO-qualifier-form3.h"
#include "ASO-qualifier-form-octets.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASO_qualifier_PR {
	ASO_qualifier_PR_NOTHING,	/* No components present */
	ASO_qualifier_PR_aso_qualifier_form1,
	ASO_qualifier_PR_aso_qualifier_form2,
	/* Extensions may appear below */
	ASO_qualifier_PR_aso_qualifier_form3,
	ASO_qualifier_PR_aso_qualifier_form_any_octets
} ASO_qualifier_PR;

/* ASO-qualifier */
typedef struct ASO_qualifier {
	ASO_qualifier_PR present;
	union ASO_qualifier_u {
		ASO_qualifier_form1_t	 aso_qualifier_form1;
		ASO_qualifier_form2_t	 aso_qualifier_form2;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		ASO_qualifier_form3_t	 aso_qualifier_form3;
		ASO_qualifier_form_octets_t	 aso_qualifier_form_any_octets;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASO_qualifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASO_qualifier;

#ifdef __cplusplus
}
#endif

#endif	/* _ASO_qualifier_H_ */
#include <asn_internal.h>
