/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ASO_qualifier_form_octets_H_
#define	_ASO_qualifier_form_octets_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ASO-qualifier-form-octets */
typedef OCTET_STRING_t	 ASO_qualifier_form_octets_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASO_qualifier_form_octets;
asn_struct_free_f ASO_qualifier_form_octets_free;
asn_struct_print_f ASO_qualifier_form_octets_print;
asn_constr_check_f ASO_qualifier_form_octets_constraint;
ber_type_decoder_f ASO_qualifier_form_octets_decode_ber;
der_type_encoder_f ASO_qualifier_form_octets_encode_der;
xer_type_decoder_f ASO_qualifier_form_octets_decode_xer;
xer_type_encoder_f ASO_qualifier_form_octets_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ASO_qualifier_form_octets_H_ */
#include <asn_internal.h>
