/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ASOI_identifier_H_
#define	_ASOI_identifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ASOI-identifier */
typedef long	 ASOI_identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASOI_identifier;
asn_struct_free_f ASOI_identifier_free;
asn_struct_print_f ASOI_identifier_print;
asn_constr_check_f ASOI_identifier_constraint;
ber_type_decoder_f ASOI_identifier_decode_ber;
der_type_encoder_f ASOI_identifier_encode_der;
xer_type_decoder_f ASOI_identifier_decode_xer;
xer_type_encoder_f ASOI_identifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ASOI_identifier_H_ */
#include <asn_internal.h>
