/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ASOI_tag_H_
#define	_ASOI_tag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ASOI-identifier.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASO_qualifier;

/* ASOI-tag */
typedef struct ASOI_tag {
	A_SEQUENCE_OF(struct ASOI_tag__Member {
		struct ASO_qualifier	*qualifier	/* OPTIONAL */;
		ASOI_identifier_t	*identifier	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASOI_tag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASOI_tag;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASO-qualifier.h"

#endif	/* _ASOI_tag_H_ */
#include <asn_internal.h>
