/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Association_data_H_
#define	_Association_data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EXTERNALt;

/* Association-data */
typedef struct Association_data {
	A_SEQUENCE_OF(struct EXTERNALt) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Association_data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Association_data;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNALt.h"

#endif	/* _Association_data_H_ */
#include <asn_internal.h>
