/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AttributeTypeAndDistinguishedValue.h"

static int
memb_contextList_constraint_6(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSET_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_valuesWithContext_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSET_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_contextList_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Context,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_contextList_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_contextList_specs_8 = {
	sizeof(struct contextList),
	offsetof(struct contextList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_contextList_8 = {
	"contextList",
	"contextList",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_contextList_tags_8,
	sizeof(asn_DEF_contextList_tags_8)
		/sizeof(asn_DEF_contextList_tags_8[0]), /* 1 */
	asn_DEF_contextList_tags_8,	/* Same as above */
	sizeof(asn_DEF_contextList_tags_8)
		/sizeof(asn_DEF_contextList_tags_8[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_contextList_8,
	1,	/* Single element */
	&asn_SPC_contextList_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_6[] = {
	{ ATF_POINTER, 1, offsetof(struct AttributeTypeAndDistinguishedValue__valuesWithContext__Member, distingAttrValue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"distingAttrValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeTypeAndDistinguishedValue__valuesWithContext__Member, contextList),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_contextList_8,
		memb_contextList_constraint_6,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contextList"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_6[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 1, 0, 0 }, /* contextList */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* distingAttrValue */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_6 = {
	sizeof(struct AttributeTypeAndDistinguishedValue__valuesWithContext__Member),
	offsetof(struct AttributeTypeAndDistinguishedValue__valuesWithContext__Member, _asn_ctx),
	asn_MAP_Member_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_6 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_6,
	sizeof(asn_DEF_Member_tags_6)
		/sizeof(asn_DEF_Member_tags_6[0]), /* 1 */
	asn_DEF_Member_tags_6,	/* Same as above */
	sizeof(asn_DEF_Member_tags_6)
		/sizeof(asn_DEF_Member_tags_6[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_6,
	2,	/* Elements count */
	&asn_SPC_Member_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_valuesWithContext_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_valuesWithContext_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_valuesWithContext_specs_5 = {
	sizeof(struct AttributeTypeAndDistinguishedValue__valuesWithContext),
	offsetof(struct AttributeTypeAndDistinguishedValue__valuesWithContext, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_valuesWithContext_5 = {
	"valuesWithContext",
	"valuesWithContext",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_valuesWithContext_tags_5,
	sizeof(asn_DEF_valuesWithContext_tags_5)
		/sizeof(asn_DEF_valuesWithContext_tags_5[0]), /* 1 */
	asn_DEF_valuesWithContext_tags_5,	/* Same as above */
	sizeof(asn_DEF_valuesWithContext_tags_5)
		/sizeof(asn_DEF_valuesWithContext_tags_5[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_valuesWithContext_5,
	1,	/* Single element */
	&asn_SPC_valuesWithContext_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AttributeTypeAndDistinguishedValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeTypeAndDistinguishedValue, type),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct AttributeTypeAndDistinguishedValue, value),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value"
		},
	{ ATF_POINTER, 2, offsetof(struct AttributeTypeAndDistinguishedValue, primaryDistinguished),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"primaryDistinguished"
		},
	{ ATF_POINTER, 1, offsetof(struct AttributeTypeAndDistinguishedValue, valuesWithContext),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_valuesWithContext_5,
		memb_valuesWithContext_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"valuesWithContext"
		},
};
static const ber_tlv_tag_t asn_DEF_AttributeTypeAndDistinguishedValue_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AttributeTypeAndDistinguishedValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* primaryDistinguished */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 3, 0, 0 } /* valuesWithContext */
};
static asn_SEQUENCE_specifics_t asn_SPC_AttributeTypeAndDistinguishedValue_specs_1 = {
	sizeof(struct AttributeTypeAndDistinguishedValue),
	offsetof(struct AttributeTypeAndDistinguishedValue, _asn_ctx),
	asn_MAP_AttributeTypeAndDistinguishedValue_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AttributeTypeAndDistinguishedValue = {
	"AttributeTypeAndDistinguishedValue",
	"AttributeTypeAndDistinguishedValue",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AttributeTypeAndDistinguishedValue_tags_1,
	sizeof(asn_DEF_AttributeTypeAndDistinguishedValue_tags_1)
		/sizeof(asn_DEF_AttributeTypeAndDistinguishedValue_tags_1[0]), /* 1 */
	asn_DEF_AttributeTypeAndDistinguishedValue_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttributeTypeAndDistinguishedValue_tags_1)
		/sizeof(asn_DEF_AttributeTypeAndDistinguishedValue_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AttributeTypeAndDistinguishedValue_1,
	4,	/* Elements count */
	&asn_SPC_AttributeTypeAndDistinguishedValue_specs_1	/* Additional specs */
};

