/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AttributeTypeAndDistinguishedValue_H_
#define	_AttributeTypeAndDistinguishedValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <ANY.h>
#include <BOOLEAN.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Context;

/* AttributeTypeAndDistinguishedValue */
typedef struct AttributeTypeAndDistinguishedValue {
	OBJECT_IDENTIFIER_t	 type;
	ANY_t	 value;
	BOOLEAN_t	*primaryDistinguished	/* DEFAULT TRUE */;
	struct AttributeTypeAndDistinguishedValue__valuesWithContext {
		A_SET_OF(struct AttributeTypeAndDistinguishedValue__valuesWithContext__Member {
			ANY_t	*distingAttrValue	/* OPTIONAL */;
			struct contextList {
				A_SET_OF(struct Context) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} contextList;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *valuesWithContext;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeTypeAndDistinguishedValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeTypeAndDistinguishedValue;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Context.h"

#endif	/* _AttributeTypeAndDistinguishedValue_H_ */
#include <asn_internal.h>
