/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Authentication-value-other.h"

static asn_TYPE_member_t asn_MBR_Authentication_value_other_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Authentication_value_other, other_mechanism_name),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other-mechanism-name"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct Authentication_value_other, other_mechanism_value),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other-mechanism-value"
		},
};
static const ber_tlv_tag_t asn_DEF_Authentication_value_other_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Authentication_value_other_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* other-mechanism-name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Authentication_value_other_specs_1 = {
	sizeof(struct Authentication_value_other),
	offsetof(struct Authentication_value_other, _asn_ctx),
	asn_MAP_Authentication_value_other_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Authentication_value_other = {
	"Authentication-value-other",
	"Authentication-value-other",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Authentication_value_other_tags_1,
	sizeof(asn_DEF_Authentication_value_other_tags_1)
		/sizeof(asn_DEF_Authentication_value_other_tags_1[0]), /* 1 */
	asn_DEF_Authentication_value_other_tags_1,	/* Same as above */
	sizeof(asn_DEF_Authentication_value_other_tags_1)
		/sizeof(asn_DEF_Authentication_value_other_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Authentication_value_other_1,
	2,	/* Elements count */
	&asn_SPC_Authentication_value_other_specs_1	/* Additional specs */
};

