/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Authentication_value_other_H_
#define	_Authentication_value_other_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Authentication-value-other */
typedef struct Authentication_value_other {
	OBJECT_IDENTIFIER_t	 other_mechanism_name;
	ANY_t	 other_mechanism_value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Authentication_value_other_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authentication_value_other;

#ifdef __cplusplus
}
#endif

#endif	/* _Authentication_value_other_H_ */
#include <asn_internal.h>
