/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Authentication_value_H_
#define	_Authentication_value_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>
#include <BIT_STRING.h>
#include "EXTERNALt.h"
#include "Authentication-value-other.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Authentication_value_PR {
	Authentication_value_PR_NOTHING,	/* No components present */
	Authentication_value_PR_charstring,
	Authentication_value_PR_bitstring,
	Authentication_value_PR_external,
	Authentication_value_PR_other
} Authentication_value_PR;

/* Authentication-value */
typedef struct Authentication_value {
	Authentication_value_PR present;
	union Authentication_value_u {
		GraphicString_t	 charstring;
		BIT_STRING_t	 bitstring;
		EXTERNALt_t	 external;
		Authentication_value_other_t	 other;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Authentication_value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authentication_value;

#ifdef __cplusplus
}
#endif

#endif	/* _Authentication_value_H_ */
#include <asn_internal.h>
