/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Concrete_syntax_name_H_
#define	_Concrete_syntax_name_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransferSyntaxName.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Concrete-syntax-name */
typedef TransferSyntaxName_t	 Concrete_syntax_name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Concrete_syntax_name;
asn_struct_free_f Concrete_syntax_name_free;
asn_struct_print_f Concrete_syntax_name_print;
asn_constr_check_f Concrete_syntax_name_constraint;
ber_type_decoder_f Concrete_syntax_name_decode_ber;
der_type_encoder_f Concrete_syntax_name_encode_der;
xer_type_decoder_f Concrete_syntax_name_decode_xer;
xer_type_encoder_f Concrete_syntax_name_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Concrete_syntax_name_H_ */
#include <asn_internal.h>
