/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Context.h"

static int
memb_contextValues_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSET_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_contextValues_3[] = {
	{ ATF_OPEN_TYPE | ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_contextValues_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_contextValues_specs_3 = {
	sizeof(struct Context__contextValues),
	offsetof(struct Context__contextValues, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_contextValues_3 = {
	"contextValues",
	"contextValues",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_contextValues_tags_3,
	sizeof(asn_DEF_contextValues_tags_3)
		/sizeof(asn_DEF_contextValues_tags_3[0]), /* 1 */
	asn_DEF_contextValues_tags_3,	/* Same as above */
	sizeof(asn_DEF_contextValues_tags_3)
		/sizeof(asn_DEF_contextValues_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_contextValues_3,
	1,	/* Single element */
	&asn_SPC_contextValues_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Context_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Context, contextType),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contextType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Context, contextValues),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_contextValues_3,
		memb_contextValues_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contextValues"
		},
	{ ATF_POINTER, 1, offsetof(struct Context, fallback),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fallback"
		},
};
static const ber_tlv_tag_t asn_DEF_Context_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Context_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* fallback */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* contextType */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 1, 0, 0 } /* contextValues */
};
static asn_SEQUENCE_specifics_t asn_SPC_Context_specs_1 = {
	sizeof(struct Context),
	offsetof(struct Context, _asn_ctx),
	asn_MAP_Context_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Context = {
	"Context",
	"Context",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Context_tags_1,
	sizeof(asn_DEF_Context_tags_1)
		/sizeof(asn_DEF_Context_tags_1[0]), /* 1 */
	asn_DEF_Context_tags_1,	/* Same as above */
	sizeof(asn_DEF_Context_tags_1)
		/sizeof(asn_DEF_Context_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Context_1,
	3,	/* Elements count */
	&asn_SPC_Context_specs_1	/* Additional specs */
};

