/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Context_list_H_
#define	_Context_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Presentation-context-identifier.h"
#include "Abstract-syntax-name.h"
#include "TransferSyntaxName.h"
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Context-list */
typedef struct Context_list {
	A_SEQUENCE_OF(struct Context_list__Member {
		Presentation_context_identifier_t	 pci;
		Abstract_syntax_name_t	 abstract_syntax;
		struct transfer_syntaxes {
			A_SEQUENCE_OF(TransferSyntaxName_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} transfer_syntaxes;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Context_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Context_list;

#ifdef __cplusplus
}
#endif

#endif	/* _Context_list_H_ */
#include <asn_internal.h>
