/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Context_H_
#define	_Context_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <BOOLEAN.h>
#include <ANY.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Context */
typedef struct Context {
	OBJECT_IDENTIFIER_t	 contextType;
	struct Context__contextValues {
		A_SET_OF(ANY_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} contextValues;
	BOOLEAN_t	*fallback	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Context_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Context;

#ifdef __cplusplus
}
#endif

#endif	/* _Context_H_ */
#include <asn_internal.h>
