/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Default_Context_List_H_
#define	_Default_Context_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Abstract-syntax-name.h"
#include "TransferSyntaxName.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Default-Context-List */
typedef struct Default_Context_List {
	A_SEQUENCE_OF(struct Default_Context_List__Member {
		Abstract_syntax_name_t	*abstract_syntax_name	/* OPTIONAL */;
		TransferSyntaxName_t	 transfer_syntax_name;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Default_Context_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Default_Context_List;

#ifdef __cplusplus
}
#endif

#endif	/* _Default_Context_List_H_ */
#include <asn_internal.h>
