/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PDV_list_H_
#define	_PDV_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransferSyntaxName.h"
#include "Presentation-context-identifier.h"
#include <ANY.h>
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDV_list__presentation_data_values_PR {
	PDV_list__presentation_data_values_PR_NOTHING,	/* No components present */
	PDV_list__presentation_data_values_PR_simple_ASN1_type,
	PDV_list__presentation_data_values_PR_octet_aligned,
	PDV_list__presentation_data_values_PR_arbitrary
} PDV_list__presentation_data_values_PR;

/* PDV-list */
typedef struct PDV_list {
	TransferSyntaxName_t	*transfer_syntax_name	/* OPTIONAL */;
	Presentation_context_identifier_t	 presentation_context_identifier;
	struct PDV_list__presentation_data_values {
		PDV_list__presentation_data_values_PR present;
		union PDV_list__presentation_data_values_u {
			ANY_t	 simple_ASN1_type;
			OCTET_STRING_t	 octet_aligned;
			BIT_STRING_t	 arbitrary;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} presentation_data_values;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDV_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDV_list;

#ifdef __cplusplus
}
#endif

#endif	/* _PDV_list_H_ */
#include <asn_internal.h>
