/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RLRE_apdu_H_
#define	_RLRE_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Release-response-reason.h"
#include "ASOI-identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASO_qualifier;
struct Association_data;

/* RLRE-apdu */
typedef struct RLRE_apdu {
	Release_response_reason_t	*reason	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ASO_qualifier	*aso_qualifier	/* OPTIONAL */;
	ASOI_identifier_t	*asoi_identifier	/* OPTIONAL */;
	struct Association_data	*user_information	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLRE_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLRE_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASO-qualifier.h"
#include "Association-data.h"

#endif	/* _RLRE_apdu_H_ */
#include <asn_internal.h>
