/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Syntactic_context_list_H_
#define	_Syntactic_context_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Context-list.h"
#include "Default-Context-List.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Syntactic_context_list_PR {
	Syntactic_context_list_PR_NOTHING,	/* No components present */
	Syntactic_context_list_PR_context_list,
	Syntactic_context_list_PR_default_contact_list
} Syntactic_context_list_PR;

/* Syntactic-context-list */
typedef struct Syntactic_context_list {
	Syntactic_context_list_PR present;
	union Syntactic_context_list_u {
		Context_list_t	 context_list;
		Default_Context_List_t	 default_contact_list;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Syntactic_context_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Syntactic_context_list;

#ifdef __cplusplus
}
#endif

#endif	/* _Syntactic_context_list_H_ */
#include <asn_internal.h>
