/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Syntactic-context-list.h"

static asn_TYPE_member_t asn_MBR_Syntactic_context_list_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Syntactic_context_list, choice.context_list),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Context_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"context-list"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Syntactic_context_list, choice.default_contact_list),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Default_Context_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"default-contact-list"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Syntactic_context_list_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* context-list */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* default-contact-list */
};
static asn_CHOICE_specifics_t asn_SPC_Syntactic_context_list_specs_1 = {
	sizeof(struct Syntactic_context_list),
	offsetof(struct Syntactic_context_list, _asn_ctx),
	offsetof(struct Syntactic_context_list, present),
	sizeof(((struct Syntactic_context_list *)0)->present),
	asn_MAP_Syntactic_context_list_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Syntactic_context_list = {
	"Syntactic-context-list",
	"Syntactic-context-list",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Syntactic_context_list_1,
	2,	/* Elements count */
	&asn_SPC_Syntactic_context_list_specs_1	/* Additional specs */
};

