/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TransferSyntaxName_H_
#define	_TransferSyntaxName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransferSyntaxName */
typedef OBJECT_IDENTIFIER_t	 TransferSyntaxName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransferSyntaxName;
asn_struct_free_f TransferSyntaxName_free;
asn_struct_print_f TransferSyntaxName_print;
asn_constr_check_f TransferSyntaxName_constraint;
ber_type_decoder_f TransferSyntaxName_decode_ber;
der_type_encoder_f TransferSyntaxName_encode_der;
xer_type_decoder_f TransferSyntaxName_decode_xer;
xer_type_encoder_f TransferSyntaxName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TransferSyntaxName_H_ */
#include <asn_internal.h>
