/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#include "User-Data.h"

static asn_TYPE_member_t asn_MBR_User_Data_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct User_Data, choice.user_information),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_User_information,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"user-information"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct User_Data, choice.simply_encoded_data),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Simply_encoded_data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"simply-encoded-data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct User_Data, choice.fully_encoded_data),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PDV_list,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fully-encoded-data"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_User_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* simply-encoded-data */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* user-information */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 } /* fully-encoded-data */
};
static asn_CHOICE_specifics_t asn_SPC_User_Data_specs_1 = {
	sizeof(struct User_Data),
	offsetof(struct User_Data, _asn_ctx),
	offsetof(struct User_Data, present),
	sizeof(((struct User_Data *)0)->present),
	asn_MAP_User_Data_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_User_Data = {
	"User-Data",
	"User-Data",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_User_Data_1,
	3,	/* Elements count */
	&asn_SPC_User_Data_specs_1	/* Additional specs */
};

