/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_User_information_H_
#define	_User_information_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Association-data.h"

#ifdef __cplusplus
extern "C" {
#endif

/* User-information */
typedef Association_data_t	 User_information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_User_information;
asn_struct_free_f User_information_free;
asn_struct_print_f User_information_print;
asn_constr_check_f User_information_constraint;
ber_type_decoder_f User_information_decode_ber;
der_type_encoder_f User_information_encode_der;
xer_type_decoder_f User_information_decode_xer;
xer_type_encoder_f User_information_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _User_information_H_ */
#include <asn_internal.h>
