/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE"
 * 	found in "../../../../utils/acse.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_User_Data_H_
#define	_User_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include "User-information.h"
#include "Simply-encoded-data.h"
#include "PDV-list.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum User_Data_PR {
	User_Data_PR_NOTHING,	/* No components present */
	User_Data_PR_user_information,
	User_Data_PR_simply_encoded_data,
	User_Data_PR_fully_encoded_data
} User_Data_PR;

/* User-Data */
typedef struct User_Data {
	User_Data_PR present;
	union User_Data_u {
		User_information_t	 user_information;
		Simply_encoded_data_t	 simply_encoded_data;
		PDV_list_t	 fully_encoded_data;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} User_Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_User_Data;

#ifdef __cplusplus
}
#endif

#endif	/* _User_Data_H_ */
#include <asn_internal.h>
